# Generated by Django 2.0.3 on 2018-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nutrition_grade', enumchoicefield.fields.EnumChoiceField(enum_class=food.models.NutritionGrade, max_length=1)),
                ('nutrition_score', models.SmallIntegerField()),
                ('url', models.URLField()),
                ('image_food', models.URLField(null=True)),
                ('image_score', models.URLField(null=True)),
                ('image_nutrition', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Category')),
            ],
            options={
                'verbose_name': 'aliment',
            },
        ),
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='MyHealthyFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
            options={
                'verbose_name': 'sélection',
            },
        ),
    ]
